[Feature] choose date frame for appointment
shilomagen/passport-extension pull request #18
Opened 2023-04-18 17:09 UTC by yair-dana

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings

2023-04-22 04:47 UTC, shilomagen commented on package.json
> +    "moment": "^2.29.4",
We are not using `moment` lib as the date utils library, we use `date-fns`. 
Can you please use `date-fns`? Thanks!

2023-04-22 04:56 UTC, shilomagen requested changes
Amazing job, let's switch to date-fns and I will merge!
Thanks @yair-dana !

2023-04-22 04:56 UTC, shilomagen commented on src/components/App/App.test.tsx
> +  const driver = new PageBaseDriver();
Beautiful

2023-04-22 04:56 UTC, shilomagen commented on src/components/DateRangePicker/DateRangePicker.test.tsx
> +  const yesterdayDate = moment().subtract(1, 'days').format(IsraelDateDigitsFormat);
```
import subDays from 'date-fns/subDays'
const yesterday = subDays(new Date(), 1)
```

2023-04-23 18:01 UTC, yair-dana commented
Hi @shilomagen ,
I made the changes following the review.
_I also handle some edge case related to storage:_
when you set a start/end date and after a few days those dates are not valid (dates that already pass).
in this case, we should generate the default dates.

WDYT following my open question?
```
There is a decision to be made on how to implement this feature - either by calling the MyVisit service with the updated Start Date, or by filtering the dates after they have been fetched from the service. (For now- both approaches are implemented)
My concern is that the startDate functionality may not be properly implemented on the MyVisit side.
```
Thanks!

2023-04-24 04:01 UTC, shilomagen approved these changes

2023-05-01 04:20 UTC, merged